### PR TITLE
Add warning for IE11 users

### PR DESCRIPTION
**Pull request by tulir**
Since some features may suddenly break for IE11, this pull request adds a warning in the about page that recommends users to switch to a modern browser. The warning is only present in the about page and doesn't actually stop the user from using the editor.

Demo available at https://dev.openapi.design/feature/ie11-warning

Preview

### CODE REVIEW

**Comment by Nazarah** [comment]
can you refix the size of the warning popup/panel? Ideally if you make the width equal to width of tabs group  in OpenAPI Designer, it would be of compact size. or perhaps show it at the top right corner, under the tabs. Right now the position and size of the warning is losing the aesthetics of the UI.

**Comment by xylix** [comment]
@Nazarah I'll try implementing a different position it today after doing some stuff to openapi/space.

**Comment by xylix** [comment]
@Nazarah It's a bit less intrusive now, but i'm going to fix the alignment tomorrow. You can see the newer version at [dev.openapi.design/feature/ie11-warning](). It also made me think, would it be a good idea to use a popup notify for this? Then it would clearly inform the user that they are using a browser that may have problems but user could then dismiss it.

**Comment by Nazarah** [comment]
@xylix I'd suggest not to use POPUP as I read an article that it actually brings bad UX in this.
What I suggest in the current solution is to add a X (or close button), so that after reading this, people can always discard the message. 
Also may be make the description text 14 px (similar to the About tab description text size). I opened it from my laptop and its too small to read now.

**Comment by tulir** [comment]
I added support for dismissing the warning and also made it a bit bigger.

Here's what it's supposed to look like:
preview

Someone should probably make sure it actually looks like that on IE.

**Comment by xylix** [comment]
Looks good to me, at least on a big enough screen. 
looksfine

**Comment by Nazarah** [comment]
Looks good enough to me. Good works guys.

**Pull request merged**
